import Head from "next/head";
import Image from "next/image";
import { v4 as uuid } from "uuid";
import styles from "../styles/pages/About.module.css";
import {
    heading,
    about,
    tracker,
    imgs,
} from "../public/text_content/aboutContent";
import Tracker from "../components/about/Tracker";
import PageHeading from "../components/PageHeading";
import PageSubHeading from "../components/PageSubHeading";

//ADD PROP "PRIOTITY" TO IMG FOR FASTER LOAD

function About() {
    const renderTrackers = () => {
        return tracker.map((tracker) => <Tracker key={uuid()} {...tracker} />);
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt - Über uns</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={"subPageContent" + " " + styles.aboutContent}>
                <section className={styles.aboutHeading}>
                    <PageHeading text={heading.heading} />
                    <p>{heading.text1}</p>
                </section>
                <section className={styles.aboutSection}>
                    <div className={styles.aboutInfo}>
                        <PageSubHeading text={about.heading} size="4.3rem" />
                        <p>{about.text1}</p>
                    </div>
                    <div className={styles.aboutInfoImg}>
                        <Image src={imgs[0].img} alt={imgs[0].alt} />
                    </div>
                </section>
                <section className={styles.aboutSection}>
                    <div className={styles.aboutTracker}>
                        {renderTrackers()}
                    </div>
                    <div className={styles.aboutTrackerImg}>
                        <Image src={imgs[1].img} alt={imgs[1].alt} />
                    </div>
                </section>
            </div>
        </div>
    );
}

export default About;
