import Head from "next/head";
import Image from "next/image";
import { v4 as uuid } from "uuid";
import styles from "../styles/pages/About.module.css";
import {
    heading,
    about,
    umweltschutz,
    tracker,
    imgs,
} from "../public/text_content/aboutContent";
import Tracker from "../components/about/Tracker";
import PageHeading from "../components/PageHeading";
import PageSubHeading from "../components/PageSubHeading";

//ADD PROP "PRIOTITY" TO IMG FOR FASTER LOAD

function About() {
    const renderTrackers = () => {
        return tracker.map((tracker) => <Tracker key={uuid()} {...tracker} />);
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt - Über uns</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link scroll={false} rel="icon" href="/favicon.ico" />
            </Head>
            <div className={"subPageContent"}>
                <section className={styles.aboutSection}>
                    <div className={styles.aboutInfo}>
                        <PageHeading text={about.heading} />
                        <p>
                            {about.text1}
                            <br />
                            {about.text2}
                        </p>
                        <div className={styles.aboutQuote}>
                            <p>{about.aboutText1}</p>
                            <span>{about.aboutAuthor1}</span>
                        </div>
                        <div className={styles.aboutQuote}>
                            <p>{about.aboutText2}</p>
                            <span>{about.aboutAuthor2}</span>
                        </div>
                    </div>
                    <div className={styles.aboutInfoImg}>
                        <Image src={imgs[0].img} alt={imgs[0].alt} />
                    </div>
                </section>
                <section className={styles.aboutSection}>
                    <div className={styles.aboutUmweltschutz}>
                        <PageSubHeading
                            text={umweltschutz.heading}
                            size="3.5rem"
                        />
                        <p>{umweltschutz.text1}</p>
                        <p>{umweltschutz.text2}</p>
                    </div>
                    <div className={styles.aboutTracker}>
                        {renderTrackers()}
                    </div>
                </section>
            </div>
        </div>
    );
}

export default About;
