import Head from "next/head";
import Link from "next/link";
import { v4 as uuid } from "uuid";
import styles from "../styles/pages/Home.module.css";
import {
    hero,
    about,
    leistungen,
    projekte,
    faq,
    kontakt,
} from "../public/text_content/indexContent";
import Separator from "../components/index/Separator";
import LeistungenItem from "../components/index/LeistungenItem";
import ProjektItem from "../components/ProjektItem";
import FaqItem from "../components/index/FaqItem";
import ArrowIcon from "../components/svgs/ArrowIcon";
import SectionHeading from "../components/SectionHeading";
import ImgBoxes from "../components/index/ImgBoxes";
import HeroHeading from "../components/index/HeroHeading";
import AboutHeading from "../components/index/AboutHeading";
import KontaktMail from "../components/index/KontaktMail";

export default function Home() {
    const renderProjects = () => {
        return projekte.projekte.map((projekt, idx) => (
            <ProjektItem key={uuid()} index={idx} {...projekt} />
        ));
    };

    const renderFaqs = () => {
        return faq.items.map((item) => <FaqItem key={uuid()} {...item} />);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt Digital</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link scroll={false} rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.indexContent}>
                <section className={styles.indexHero}>
                    <ImgBoxes />
                    <HeroHeading text={hero.heading} />
                    <p className={styles.headingHeroSub}>{hero.text1}</p>
                    <Link scroll={false} href="/kontakt" passHref>
                        <a className="bold">
                            <div className="arrow"></div>
                            <ArrowIcon />
                            <span>{hero.linkText1}</span>
                        </a>
                    </Link>
                </section>
                <section className={styles.indexAbout}>
                    <div className={styles.indexAboutLeft}>
                        <AboutHeading text={about.heading} />
                        <Link scroll={false} href="/about" passHref>
                            <a className="thin">
                                <div className="arrow"></div>
                                <ArrowIcon />
                                <span>{about.linkText1}</span>
                            </a>
                        </Link>
                    </div>
                    <p>{about.text1}</p>
                </section>
                <Separator />
                <section className={styles.indexLeistungen}>
                    <SectionHeading text={leistungen.heading} />
                    <Link scroll={false} href="/leistungen" passHref>
                        <a className="thin">
                            <div className="arrow"></div>
                            <ArrowIcon />
                            <span>{leistungen.linkText1}</span>
                        </a>
                    </Link>
                    <div className={styles.LeistungenItems}>
                        <LeistungenItem
                            heading={leistungen.subHeading1}
                            text={leistungen.text1}
                            img={leistungen.img1}
                            alt={leistungen.alt1}
                        />
                        <LeistungenItem
                            heading={leistungen.subHeading2}
                            text={leistungen.text2}
                            img={leistungen.img2}
                            alt={leistungen.alt2}
                        />
                        <LeistungenItem
                            heading={leistungen.subHeading3}
                            text={leistungen.text3}
                            img={leistungen.img3}
                            alt={leistungen.alt3}
                        />
                    </div>
                </section>
                <Separator />
                <section className={styles.indexProjekte}>
                    <SectionHeading text={projekte.heading} />
                    <Link scroll={false} href="/projekte" passHref>
                        <a className="thin">
                            <div className="arrow"></div>
                            <ArrowIcon />
                            <span>{projekte.linkText1}</span>
                        </a>
                    </Link>
                    <div className={styles.indexProjekteItems}>
                        {renderProjects()}
                    </div>
                </section>
                <Separator />
                <section className={styles.indexFaq}>
                    <SectionHeading text={faq.heading} />
                    <div className={styles.indexFaqItems}>{renderFaqs()}</div>
                </section>
                <Separator />
                <section className={styles.indexKontakt}>
                    <SectionHeading text={kontakt.heading} />
                    <SectionHeading text={kontakt.subHeading1} />
                    <div>
                        <a
                            className={styles.kontaktMail}
                            href="mailto:kontakt@fensterblatt.digital"
                        >
                            <KontaktMail text="kontakt@fensterblatt.digital" />
                        </a>
                    </div>
                    <Link scroll={false} href="/kontakt" passHref>
                        <a className="bold">
                            <div className="arrow"></div>
                            <ArrowIcon />
                            <span>{kontakt.linkText1}</span>
                        </a>
                    </Link>
                </section>
            </div>
        </div>
    );
}
