import Head from "next/head";
import styles from "../styles/pages/Kontakt.module.css";
import { info, form, link } from "../public/text_content/kontaktContent";
import { useState } from "react";
import ArrowIcon from "../components/svgs/ArrowIcon";
import PageHeading from "../components/PageHeading";

function KontaktPage() {
    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const [msg, setMsg] = useState("");

    const handleSubmit = async (e) => {
        e.preventDefault();
        fetch("/api/mail", {
            method: "post",
            body: JSON.stringify({ name, email, msg }),
        });
        setName("");
        setEmail("");
        setMsg("");
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt - Kontakt</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="subPageContent">
                <section className={styles.kontakt}>
                    <div className={styles.kontaktInfo}>
                        <PageHeading text={info.heading} />
                        <p>{info.text1}</p>
                        <div className={styles.kontaktInfoItems}>
                            <span>
                                <a href="mailto:kontakt@fensterblatt.digital">
                                    0511 - 3354372
                                </a>
                            </span>
                            <span>
                                <a href="mailto:kontakt@fensterblatt.digital">
                                    kontakt@fensterblatt.digital
                                </a>
                            </span>
                            <span>
                                <a href="https.//xing.com/">Xing</a>
                            </span>
                        </div>
                    </div>
                    <form
                        className={styles.kontaktForm}
                        onSubmit={handleSubmit}
                    >
                        <label htmlFor="name">{form.labelName}</label>
                        <input
                            id="name"
                            name="name"
                            type="text"
                            required
                            placeholder={form.placeholderName}
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                        />
                        <label htmlFor="email">{form.labelMail} </label>
                        <input
                            id="email"
                            name="email"
                            type="email"
                            required
                            placeholder={form.placeholderMail}
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                        />
                        <label htmlFor="msg">{form.labelMsg}</label>
                        <textarea
                            id="msg"
                            name="msg"
                            type="msg"
                            rows="12"
                            placeholder={form.placeholderMsg}
                            value={msg}
                            onChange={(e) => setMsg(e.target.value)}
                        ></textarea>
                        <button className="bold" type="submit">
                            <div className="arrow"></div>
                            <ArrowIcon />
                            <span>{link.linkText1}</span>
                        </button>
                    </form>
                </section>
            </div>
        </div>
    );
}

export default KontaktPage;
