import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Kontakt.module.css";
import { info, form, link } from "../public/text_content/kontaktContent";
import { useState } from "react";
import ArrowIcon from "../components/ArrowIcon";
import XingIcon from "../components/kontakt/XingIcon";

function KontaktPage() {
    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const [msg, setMsg] = useState("");

    const handleSubmit = async (e) => {
        e.preventDefault();
        fetch("/api/mail", {
            method: "post",
            body: JSON.stringify({ name, email, msg }),
        });
        setName("");
        setEmail("");
        setMsg("");
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt - Kontakt</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="subPageContent">
                <section className={styles.kontakt}>
                    <div className={styles.kontaktInfo}>
                        <h1 className="subH1">{info.heading}</h1>
                        <p>{info.text1}</p>
                        <span className={styles.Mail}>
                            kontakt@Fensterblatt.digital
                        </span>
                        <div className={styles.Icons}>
                            <Link
                                scroll={false}
                                href="https://xing.de"
                                passHref
                            >
                                <a>
                                    <XingIcon />
                                </a>
                            </Link>
                        </div>
                    </div>
                    <form
                        className={styles.kontaktForm}
                        onSubmit={handleSubmit}
                    >
                        <label htmlFor="name">{form.labelName}</label>
                        <input
                            id="name"
                            name="name"
                            type="text"
                            required
                            placeholder={form.placeholderName}
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                        />
                        <label htmlFor="email">{form.labelMail} </label>
                        <input
                            id="email"
                            name="email"
                            type="email"
                            required
                            placeholder={form.placeholderMail}
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                        />
                        <label htmlFor="msg">{form.labelMsg}</label>
                        <textarea
                            id="msg"
                            name="msg"
                            type="msg"
                            rows="12"
                            placeholder={form.placeholderMsg}
                            value={msg}
                            onChange={(e) => setMsg(e.target.value)}
                        ></textarea>
                        <button className="bold" type="submit">
                            <ArrowIcon />
                            {link.linkText1}
                        </button>
                    </form>
                </section>
            </div>
        </div>
    );
}

export default KontaktPage;
