import Head from "next/head";
import { v4 as uuid } from "uuid";
import styles from "../styles/Leistungen.module.css";
import { heading, items } from "../public/text_content/leistungenContent";
import LeistungenItem from "../components/leistungen/LeistungenItem";

function Leistungen() {
    const renderLeistungenItems = () => {
        return items.map((item, idx) => (
            <LeistungenItem key={uuid()} index={idx} {...item} />
        ));
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Fensterblatt - Leistungen</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="subPageContent">
                <section className={styles.leistungenHeading}>
                    <h1 className="subH1">Leistungen</h1>
                    <p>{heading.text1}</p>
                </section>
                <section className={styles.leistungenItems}>
                    {renderLeistungenItems()}
                </section>
            </div>
        </div>
    );
}

export default Leistungen;
